###
POST http://localhost:5000/api/v1/auth/login
content-type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456"
}
###
POST http://localhost:5000/api/v1/auth/signup
content-type: application/json

{
    "email": "teacher@gmail.com",
    "password": "123456",
    "firstName": "toni",
    "lastName": "dev",
    "dateOfBirth": "1/1/1980",
    "address": {
        "street": "le ngan",
        "city": "da nang",
        "country": "vietanm"
    },
    "role": 3
}
###
POST http://localhost:5000/api/v1/courses
content-type: application/json

{
    "title": "hoc lap trinh js",
    "description": "hoc lap trinh js tai GuruAccademy",
    "author": "61475af8301f7ba3e1c67a6b",
    "topic": "6148239e9d4e31a30142c0b4",
    "tags": "tags",
    "price": "1000",
    "discount": "10",
    "learnersDetail": [],
    "streams": [],
    "feedbacks": [],
    "chapters": []
}
###
GET http://localhost:5000/api/v1/course-categories
###
GET http://localhost:5000/api/v1/course-categories/:categorySlugOrId
###
GET http://localhost:5000/api/v1/courses/all